yetibot/yetibot

src/yetibot/commands/stock.clj
Took me a bit to handle edge conditions. =) Let me know if there is a better way to handle the if after hours price is available logic:
(if (empty? el) l el)
=> Adding after hours price and change

src/yetibot/api/github.clj
-  [this](https://github.com/devth/yetibot/blob/master/src/yetibot/api/github.clj#L37) should be taken out and all the library calls should be placed with the `with-url` macro provided by the tentacles library
Was tested against the default api (this could be problematic with respect to proving that it works against any other url)
=> fix for #585

README.md, project.clj, src/yetibot/commands/emoji.clj
Completes #78 
`!emoji` Commands are:
`!emoji tag [-i] <query>`              - search by tag
`!emoji description [i] <query>` - search by description
`!emoji alias <query>`                 - search by alias
Note: The `-i` flag returns both the unicode and a list of aliases.
Ommiting the flag returns just the unicode.
Any other emoji-related commands we might need?
=> Emoji Databse 

src/yetibot/commands/emoji.clj, test/yetibot/test/commands/emoji.clj
- Created Tests for all functions located in commands/emoji.clj
- Had to sanitize input for two functions in emoji.clj so they wouldn't throw exceptions
when passed certain input
=> !Emoji Command tests

src/yetibot/api/jira.clj
Changing subtask jira parameter to optional.
=> Change subtask jira parameter to optional

src/yetibot/commands/urban_thesaurus.clj, test/yetibot/test/commands/urban_thesaurus.clj
For me now, the simplest solution was to create an http request to the api instead of the solution in #613.
I will try to look into this issue and see if i can implement it and replace this command with an alias later.
=> Add urbanthesaurus.org command #649

project.clj
Adding alias to run midje tests using `lein test`
=> Add alias for midje tests to run with lein test

project.clj
=> Bump Clojure version

doc/CHANGELOG.md, project.clj, src/yetibot/api/google/gcs.clj, src/yetibot/commands/google/gcs.clj
Related to https://github.com/yetibot/yetibot/issues/719
=> Add gcs command

src/yetibot/commands/karma.clj, test/yetibot/test/commands/karma.clj
@devth over to you, please.
Testing at the command layer, but via `:result/data`, _and_ also at the model layer may be excessive, yet also skip a useful check on output formatting... I went back and forth.  Thoughts welcome, as always :)
=> Karma now provides data for downstream commands; closes: #786

src/yetibot/commands/pirate.clj, src/yetibot/commands/weather.clj
=> Cleaned up some namespace aliases

src/yetibot/commands/karma.clj, src/yetibot/commands/karma/specs.clj, src/yetibot/models/karma.clj, test/yetibot/test/commands/karma.clj, test/yetibot/test/commands/karma/specs.clj, test/yetibot/test/models/karma.clj
@devth, new PR as I rebased my feature branch to flatten some commits.
=> karma tighter parsing

src/yetibot/commands/weather.clj
This removes the manual encoding of query params and building of urls and instead uses `clj-http`'s built in capabilities. It also bakes in default query params like `key` and `units` into `get-json` and allows callers to specify any additional `clj-http` options as needed.
=> Use clj-http to encode query params

src/yetibot/commands/weather.clj
Result of the livecoding session!
=> Add weather forecast

src/yetibot/api/jira.clj, src/yetibot/commands/jira.clj
Fix https://github.com/yetibot/yetibot/issues/866
=> Add ability to specify reporter when creating jira issues

src/yetibot/commands/weather.clj, src/yetibot/commands/weather/formatters.clj, test/yetibot/test/commands/weather.clj
=> Add conditions description to weather forecast

project.clj, src/yetibot/commands/clojure.clj, test/yetibot/test/commands/clojure.clj
Fixes https://github.com/yetibot/yetibot/issues/878 (hopefully - need to run on DigitalOcean to confirm)
=> Upgrade clojail to fork and use simpler sandbox

Dockerfile, project.clj
Fix https://github.com/yetibot/yetibot/issues/878
=> Specify the use of a local java.policy when running in Docker via new profile

Dockerfile, src/yetibot/api/github.clj, src/yetibot/commands/github.clj
Result of livecoding session at Clojure/north!
=> Add initial GitHub search command

src/yetibot/commands/clojure.clj
Fix https://github.com/yetibot/yetibot/issues/943
=> Fix data on clj when data is a lazy seq

project.clj, src/yetibot/commands/stock.clj
https://www.alphavantage.co/documentation/
=> Fix stock by switching to Alpha Vantage API

project.clj, src/yetibot/api/aws.clj, src/yetibot/api/catchpoint.clj, src/yetibot/api/ebay.clj, src/yetibot/api/giphy.clj, src/yetibot/api/github.clj, src/yetibot/api/google.clj, src/yetibot/api/google/gcs.clj, src/yetibot/api/jira.clj, src/yetibot/api/s3.clj, src/yetibot/commands/emoji.clj, src/yetibot/commands/features.clj, src/yetibot/commands/pagerduty.clj, src/yetibot/commands/stock.clj, src/yetibot/commands/weather.clj, src/yetibot/commands/wolfram.clj, src/yetibot/commands/wordnik.clj, src/yetibot/models/imgflip.clj, src/yetibot/models/jenkins.clj, src/yetibot/models/twitter.clj, test/yetibot/test/commands/clojure.clj, test/yetibot/test/commands/emoji.clj
Corresponding PR in yetibot.core: https://github.com/yetibot/yetibot.core/pull/106
=> Switch from schema to clojure.spec

.travis.yml, Dockerfile, project.clj
=> Add healthcheck to Dockerfile

src/yetibot/commands/time.clj
Command returns formatted date time in server timezone.
Closes #830.
=> Implement !time command.

project.clj, src/yetibot/commands/cowsay.clj
=> Implement cowsay command.

src/yetibot/api/jira.clj, src/yetibot/commands/jira.clj
Fix https://github.com/yetibot/yetibot/issues/1003
=> Add JIRA priority support

src/yetibot/commands/xkcd.clj
I want to see various xkcd comics at work
Add an index, so I can see any specific one
If there is a 404, I will present the relevent xkcd comic
Used https://gist.github.com/devth/bd154e76536eed783974764dc6e6a2d3 as a starting point
=> Get xkcd comic by index

src/yetibot/commands/xkcd.clj
I want to see random XKCD comics
Use an atom to store the last known date of the latest comic
I'm then using this number to get a random comic
The underlying assumption is the ids are sequential, but they are since this is how the web ui works (the next and back buttons) see: https://xkcd.com/2309/#
Also, I've opened up two pull requests. This one and #1022 -- this one builds on the last one. 
Also appreciate the lack of tests, can add them for the helper stuff, and even refactor a bit more.
=> Xkcd random

src/yetibot/commands/wolfram.clj, test/yetibot/test/commands/wolfram.clj
Resolves issue #998 
Populates result/data with unmodified :queryresult object from Wolfram API call.
Sends textual data to user when present, otherwise link to image.
=> Improve wolfram command

src/yetibot/models/imgflip.clj
3 is too low, 69 is just right
=> Update imgflip pages scrapped from 3 -> 69
