yetibot/yetibot

src/yetibot/commands/twitter.clj, src/yetibot/models/twitter.clj
- Feature so that user is able to display a tweet just by the id
Command template is `!twitter  display <id>`
- Command name `show` was already taken up, so changed command name to `display`
- tested on a local instance
=> twitter show <id> #552

config/config-sample.edn, src/yetibot/api/google.clj, src/yetibot/commands/google.clj, test/yetibot/test/api/google.clj, test/yetibot/test/commands/google.clj
To create  `google` commands that is able to search both text and images. 
Users should also be able to customize the search engine via the config file.
User should  be able to put in cli type options while using the `search` and `image` (image search command)
User should be able to set options for search via the appropriate commands 
- `google search <query>` returns at-most 10 results (because of custom engine API limitation) with a `title`,`link` and `snippet` for each result.
-   `google image <query>` now searches for images based on what the query is. The image results are displayed in a different order than the vanilla search one due to rendering weirdness on slack
- config is checked for the existence of two keys in existence in addition  to the config-validation function  that …
=>  Google custom search (images and text) #524 

project.clj, src/yetibot/commands/github.clj, test/yetibot/test/commands/github.clj
To make sure the `gh stats` polls for the contributor stats in the scenario
github requires time to process/crunch the stats numbers
- gh stats is now a polling function with a set number of tries
after which the function gives up and outputs the existing
try-after-some-time message
- tests are in order for the polling for the stats feature
- project dependencies now include robert bruce (the intelligent polling library)
-  Add some organization like `Netflix` to your `orgs` list in the `config.edn`
- start yetibot
- `gh repos Netflix` to get a list of all their repos 
- randomly samply a few off the above mentioned list and run `gh stats` on them
- Expected results are the ui should take a few seconds more than usual to get back to you with the stats if you do not see an (almost) …
=> code for issue #563

doc/GETTING_STARTED.md
Without the closing '}' I get an error:
`ERROR [yetibot.core.util.config:29] - Failed loading config:  java.lang.RuntimeException: Map literal must contain an even number of forms`
Referenced in #627
=> Add  Missing '}'

src/yetibot/commands/json.clj
-Idea from: mmazi/rescu#54
Not sure if this is something that clj-http should be stripping out
on their end? This might just be a hack, and there is a better way
to go about this?
Also, adding [cheshire] as a dependency might fix it as well, although when I
tried that, it still gave the same error (cheshire is a dependency
of clj-http when using the :as :json feature of clj-http/get
see [here](https://github.com/dakrone/clj-http#optional-dependencies) )
=> Fix For Issue #620

src/yetibot/commands/json.clj, src/yetibot/commands/meme.clj, src/yetibot/models/imgflip.clj
Also allows for scraping any number of pages
Hard-coded at 3 right now, but can be changed in future if needed (is this necessary?)
=> Fix For Issue #455

src/yetibot/commands/json.clj, test/yetibot/test/commands/json.clj
Add convertion to keywords in json parse command to allow use with `curl` and `json path` commands.
Ex.: `!curl url | json parse | json path $..words`
Without the keywords commands. It was generating the parsed json with the following structure:
`{key "value"}`
And when trying to use `json path`, the command didn't work well.
=> Add convertion to keywords in json parse command

src/yetibot/commands/catfacts.clj
This is an attempt to fix issue #669 "catfact is dead 😿" by switching from the dead catfacts-api to catfacts.info.
Since [catfacts.info](http://www.catfact.info/) doesn't allow for random catfacts requests, it will instead fetch for a single page through http://www.catfact.info/api/v1/facts.json?page=1&per_page=1 with a random page id from 1 to total. The first request made will do two requests, one to obtain the total number of facts to generate the random page id with, and then a request for the random fact. After that point, the total number is stored in an atom, and updated each time a request is made.
Long live catfacts 🐱
=> Fix for issue #669

doc/GETTING_STARTED.md
A tiny change I had to make to get Yetibot, running locally via `docker-compose`, to connect to my Slack workspace.  These vars are correctly specified in `doc/DOCKER.md`.
Thanks for such a fun project!
=> Fixed Docker Compose env var Slack example

src/yetibot/api/github.clj, src/yetibot/commands/github.clj
Hey guys,
Sorry that it took so long for me to come back for this PR but I wanted to get a little bit acquainted with the project (real beginner here ^^). In the end though, it feels good to learn some new stuff ;-) and fortunately, here is the first PR I can come up with.
This one is related to issue #729 : we wanted a command for fetching infos about the latest release on a github repository.
The syntax for the command is quite simple : 
`!gh releases org-name/repo`
Here are some screenshots of how it renders :
1. When simply asking the bot to fetch the latest release info
2. When asking for release infos which are, unfortunately, unavailable
3. When used with the already existing `cron` command
I hope my code is not too ugly ^^ but anyway, feel free to let me know of any changes that …
=> Add command for fetching the latest release info from a github repo

project.clj, src/yetibot/models/karma.clj, test/yetibot/test/models/karma.clj
=> Karma leaderboard should not including scores of 0 or less

project.clj, src/yetibot/commands/pagerduty.clj, test/yetibot/test/commands/pagerduty.clj
=> Add initial pagerduty support with teams and users

project.clj, src/yetibot/commands/scala.clj
hey guys,
Sorry that it took so long to deliver this one but I had some fun (and struggles ^^) learning some new stuff along the way while implementing it ;-)...
by the way, thanks a lot @devth for helping me out when I was stuck : you provided valuable insights ... I owe you a beer (or two hehe)
So, what do we have here :
- First of all, instead of using the now _deprecated_ `scalakata` API, we now target the new `scastie` Scala evaluation API which uses _Server-Sent Events (SSE)_ for sending back the results.
- A small utilitiy lib, `[io.nervous/kvlt "0.1.4"]`, has then been introduced to handle these SSEs. `kvlt` provides an abstraction based on `core.async` channels for handing out the incoming events from the server.
- There are some _parameters_ related to the evaluation API (api …
=> Fix Scala evaluation command

.gitignore, doc/CHANGELOG.md, project.clj, src/yetibot/commands/weather.clj
Basically delaying `first` and `:data` in the old `200 (first (:data body))` because other API calls need the full response (such as upcoming forecast).
=> Weather tweaks

src/yetibot/commands/weather.clj
Generalize `current-by-name` / `current-by-pc` so we can use them for other API resources, such as upcoming forecast.
=> Factor weather up a bit

doc/CHANGELOG.md, src/yetibot/commands/weather.clj
If API quota is passed, Weatherbit will return a `:body` like:
```clojure
{:status_code 429
:status_message "Your request count (1007) is over the allowed limit of 1000 per day - Upgrade your key, or retry after 1343.2 minutes"}
```
This change handles it, e.g.:
=> Add error handling support for http 429

src/yetibot/commands/aws/formatters.clj
=> Add missing dep for yetibot.api.aws

src/yetibot/commands/cljquotes.clj
With quotes sourced from https://github.com/Azel4231/clojure-quotes
=> Add a cljquotes command for spouting random quotes about Clojure

Dockerfile
I talked with @devth about this at Clojure/North, while I was debugging the startup of the app.
=> Dockerfile CMD should be list separated by commas.

doc/CHANGELOG.md, project.clj
Testing out the upgrade on a branch since the [changes in yetibot/core](https://github.com/yetibot/yetibot.core/blob/master/doc/CHANGELOG.md#yetibotcore-201909131827571838a79) are significant!
=> Upgrade to yetibot/core "20190913.182757.1838a79"

.github/workflows/repository-dispatch.yml
Merging WIP as `repository_dispatch` events only run on master:
https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows#repository_dispatch
=> Add repo dispatch action to bump yetibot/core
